### ISSUE TITLE
TODO: backup data

### ISSUE THREAD

**Issue by noraworld** [noraworld/dotfiles#6]
# client (macOS)
- [ ] Karabiner-Elements config (manually or mackup)
- [ ] Homebrew Formulae list (brew bundle)
- [ ] Installed applications list (brew bundle)
- [ ] Installed Mac App Store applications list (brew bundle)
- [ ] Application settings (mackup)

# server (Ubuntu)
- [ ] Apt packages list (maybe manually)
- [ ] systemd config (manually, other repository)

**Comment by noraworld** [comment]
This is just a memo.
